# Generated by Django 5.0.6 on 2024-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsmodels',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
