# Generated by Django 5.0.6 on 2024-06-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField()),
                ('isbn', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
