# Generated by Django 5.0.6 on 2024-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_booksmodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
