# Generated by Django 5.0.6 on 2024-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_booksmodel_author_alter_booksmodel_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='in_stock',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
